const { handler } = require('./index');

// Test event
const testEvent = {
    body: JSON.stringify({
        html: `
            <!DOCTYPE html>
            <html>
            <head>
                <title>Test PDF</title>
                <style>
                    body { font-family: Arial, sans-serif; padding: 20px; }
                    h1 { color: #333; }
                </style>
            </head>
            <body>
                <h1>Hello from Lambda!</h1>
                <p>This is a test PDF generated by the AWS Lambda function.</p>
                <p>Timestamp: ${new Date().toISOString()}</p>
            </body>
            </html>
        `,
        options: {
            format: 'A4',
            filename: 'test-lambda.pdf'
        }
    })
};

// Test the handler
(async () => {
    try {
        console.log('🧪 Testing Lambda function locally...');
        
        const result = await handler(testEvent);
        
        console.log('✅ Lambda function executed successfully!');
        console.log('Status Code:', result.statusCode);
        console.log('Headers:', result.headers);
        console.log('Body length:', result.body.length);
        console.log('Is Base64 Encoded:', result.isBase64Encoded);
        
        if (result.statusCode === 200) {
            // Save the PDF to file for inspection
            const fs = require('fs');
            const pdfBuffer = Buffer.from(result.body, 'base64');
            fs.writeFileSync('test-output.pdf', pdfBuffer);
            console.log('📄 PDF saved as test-output.pdf');
        }
        
    } catch (error) {
        console.error('❌ Test failed:', error);
    }
})();
